#!/bin/sh

art_path="$HOME/.config/spotifyd/current.jpg"

if [[ "$PLAYER_EVENT" = "start" ]] || [[ "$PLAYER_EVENT" = "change" ]]; then
	status="Now playing"

elif [[ "$PLAYER_EVENT" = "stop" ]]; then
	status="Paused"

else
	status="Unknown"
fi

metadata=$(playerctl metadata -f "{{ mpris:artUrl }}\{{ title }}\{{ artist }}" -p "spotifyd")
art_url="$(cut -d'\' -f1 <<< $metadata)"
song="$(cut -d'\' -f2 <<< $metadata)"
artist="$(cut -d'\' -f3 <<< $metadata)"

curl -s -o "$art_path" "$art_url" > /dev/null

notify-send "Spotify" "$status\n$song by $artist" --icon="$art_path"

exit 0

